# Default TNGP Config File. Used if no config file is provided to the broker.

# Networking configuration ----------------------------

[network]
hostname = "0.0.0.0"
sendBufferSize = 128

[network.clientApi]
port = 6665
receiveBufferSize = 16

[network.managementApi]
host = "localhost"
port = 6666
receiveBufferSize = 16

[network.replicationApi]
host = "localhost"
port = 6667
receiveBufferSize = 16

[network.gossip]
initialContactPoints = [
  "localhost:5555"
]
peersStorageFile = "/tmp/6666.tngp"

# System Configuration --------------------------------

[threading]
numberOfThreads = 2
maxIdleTimeMs = 100
idleStrategy = "BACKOFF"

[metrics]
useTempCountersFile = true

# Log Configuration -----------------------------------

[logs]
logWriteBufferSize = 256
defaultLogSegmentSize = 512

[[log]]
name = "default-task-queue-log"
id = 0
logDirectory = "/tmp/tngp-6666-task"

[snapshot]
useTempSnapshotDirectory = true

# Task Queues ------------------------------------------

[task-queues]
numberOfWorkers = 1
perWorkerResponsePoolCapacity = 32

[[task-queue]]
logName = "default-task-queue-log"
useTempIndexFile = true