# Default TNGP Config File. Used if no config file is provided to the broker.

# Global configuration --------------------------------

[global]
globalUseTemp = true

# Networking configuration ----------------------------

[network]
host = "0.0.0.0"
sendBufferSize = 128

[network.clientApi]
port = 51015
receiveBufferSize = 16
controlMessageRequestTimeoutInMillis = 10000

[network.managementApi]
host = "localhost"
port = 51016
receiveBufferSize = 16

[network.replicationApi]
host = "localhost"
port = 51017
receiveBufferSize = 16

[network.gossip]

[network.management]


# System Configuration --------------------------------

[threading]
numberOfThreads = 2
maxIdleTimeMs = 100
idleStrategy = "BACKOFF"

[metrics]

# Log Configuration -----------------------------------

[logs]
defaultLogSegmentSize = 512

[snapshot]

# Topic Subscriptions ------------------------------------------

[subscriptions]
useTempSnapshotFile = true
