# Default TNGP Config File. Used if no config file is provided to the broker.

# Networking configuration ----------------------------

[network]
host = "0.0.0.0"
sendBufferSize = 128

[network.clientApi]
port = 8080
receiveBufferSize = 16

[network.managementApi]
host = "localhost"
port = 5555
receiveBufferSize = 16

[network.replicationApi]
host = "localhost"
port = 5556
receiveBufferSize = 16

[network.gossip]
initialContactPoints = [
  "localhost:51016"
]
peersStorageFile = "/tmp/tngp/5555/gossip/5555.tngp"

[network.management]
metaDirectory = "/tmp/tngp/5555/meta"

# System Configuration --------------------------------

[threading]
numberOfThreads = 2
maxIdleTimeMs = 100
idleStrategy = "BACKOFF"

[metrics]
useTempCountersFile = true

# Log Configuration -----------------------------------

[logs]
defaultLogSegmentSize = 512
logDirectories = [
    "/tmp/tngp/5555/logs"
]
indexDirectory = "/tmp/tngp/5555/index"

[snapshot]
useTempSnapshotDirectory = true

# Topic Subscriptions ------------------------------------------

[subscriptions]
useTempSnapshotFile = true
