# Default TNGP Config File. Used if no config file is provided to the broker.

# Networking configuration ----------------------------

[network]
host = "0.0.0.0"
sendBufferSize = 128

[network.clientApi]
port = 7776
receiveBufferSize = 16

[network.managementApi]
host = "localhost"
port = 7777
receiveBufferSize = 16

[network.replicationApi]
host = "localhost"
port = 7778
receiveBufferSize = 16

[network.gossip]
initialContactPoints = [
  "localhost:51016"
]
peersStorageFile = "/tmp/tngp/7777/gossip/7777.tngp"

[network.management]
metaDirectory = "/tmp/tngp/7777/meta"

# System Configuration --------------------------------

[threading]
numberOfThreads = 2
maxIdleTimeMs = 100
idleStrategy = "BACKOFF"

[metrics]
useTempCountersFile = true

# Log Configuration -----------------------------------

[logs]
defaultLogSegmentSize = 512
logDirectories = [
    "/tmp/tngp/7777/logs"
]
indexDirectory = "/tmp/tngp/7777/index"

[snapshot]
useTempSnapshotDirectory = true

# Topic Subscriptions ------------------------------------------

[subscriptions]
useTempSnapshotFile = true
