# Default TNGP Config File. Used if no config file is provided to the broker.

# Networking configuration ----------------------------

[network]
hostname = "0.0.0.0"
sendBufferSize = 128

[network.clientApi]
port = 51015
receiveBufferSize = 16

# System Configuration --------------------------------

[threading]
numberOfThreads = 2

[metrics]
useTempCountersFile = true

# Log Configuration -----------------------------------

[logs]
logWriteBufferSize = 256
defaultLogSegmentSize = 512

[[log]]
name = "default-task-queue-log"
id = 0
useTempLogDirectory = true

[[log]]
name = "default-wf-type-log"
id = 1
useTempLogDirectory = true

[[log]]
name = "default-wf-instance-log"
id = 2
useTempLogDirectory = true

# Task Queues ------------------------------------------

[task-queues]
numberOfWorkers = 1
perWorkerResponsePoolCapacity = 32

[[task-queue]]
name = "default"
id = 0
logName = "default-task-queue-log"

# Workflow Repositories ---------------------------------

[workflow]
numberOfWorkers = 1
perWorkerResponsePoolCapacity = 32

[[workflow-repository]]
name = "default"
id = 0
logName = "default-wf-type-log"

[[workflow-runtime]]
name = "default"
id = 0
workflowRepository = "default" 
logName = "default-wf-instance-log"
