[book]
title = "Zeebe Documentation"
description = "Zeebe is an orchestration engine for distributed microservices"

[preprocessor.commit-hash]
command = "./preprocessors/commit-hash.py"

[output.html]
additional-css = ["custom.css"]
additional-js = ["highlight.protobuf.js"]
git-repository-url = "https://github.com/zeebe-io/zeebe/tree/develop/docs"
