---
baseurl: "/manual/"
languageCode: "en-us"
title: "Camunda Tngp Documentation"
theme: "camunda"

blackfriday:
  plainIDAnchors: true

params:
  sections:
    - id: "manual"
      name: "Manual"
      url: "/manual"
  section:
    id: "manual"
  github:
    repositoryName: "camunda-tngp/camunda-tngp"
    branch: "master/docs"
...
