name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          export CGO_ENABLED=0
          CGO_ENABLED=0
          ORG_DIR=/go/src/github.com/zeebe-io
          mkdir -p /go/src/github.com/zeebe-io
          ln -s . /go/src/github.com/zeebe-io/zeebe
          go get -u github.com/jstemmer/go-junit-report
          cd /go/src/github.com/zeebe-io/zeebe/clients/go
          PREFIX=github.com/zeebe-io/zeebe/clients/go
          EXCLUDE=
          for file in {internal,cmd/zbctl/internal}/*
          EXCLUDE=github.com/zeebe-io/zeebe/clients/go/internal/containersuite,
          for file in {internal,cmd/zbctl/internal}/*
          EXCLUDE=github.com/zeebe-io/zeebe/clients/go/internal/containersuite,github.com/zeebe-io/zeebe/clients/go/internal/mock_pb,
          for file in {internal,cmd/zbctl/internal}/*
          EXCLUDE=github.com/zeebe-io/zeebe/clients/go/internal/containersuite,github.com/zeebe-io/zeebe/clients/go/internal/mock_pb,github.com/zeebe-io/zeebe/clients/go/internal/utils,
          for file in {internal,cmd/zbctl/internal}/*
          EXCLUDE=github.com/zeebe-io/zeebe/clients/go/internal/containersuite,github.com/zeebe-io/zeebe/clients/go/internal/mock_pb,github.com/zeebe-io/zeebe/clients/go/internal/utils,github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/internal/commands,
          /usr/bin/gocompat compare --go1compat --exclude-package=github.com/zeebe-io/zeebe/clients/go/internal/containersuite,github.com/zeebe-io/zeebe/clients/go/internal/mock_pb,github.com/zeebe-io/zeebe/clients/go/internal/utils,github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/internal/commands, ./...
          cd /go/src/github.com/zeebe-io/zeebe/clients/go/cmd/zbctl
          ./build.sh
          dirname ./build.sh
          SRC_DIR=.
          DIST_DIR=./dist
          VERSION=development
          git rev-parse HEAD
          COMMIT=$GITHUB_SHA
          mkdir -p ./dist
          CGO_ENABLED=0
          GOOS=linux
          GOARCH=amd64
          go build -mod=vendor -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/internal/commands.Version=development -X github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/internal/commands.Commit='"$GITHUB_SHA"'' -o ./dist/zbctl ./main.go
      - name: Test
        run: ./dist/zbctl
